import type IElement from './models/IElement';

export default <IElement[]>[
  {
    name: 'Attinio',
    symbol: 'Ac',
    atomicNumber: 89,
    atomicWeight: 227,
    oxidationStates: [3],
    rawType: 'Actinide',
  },
  {
    name: 'Alluminio',
    symbol: 'Al',
    atomicNumber: 13,
    atomicWeight: 26.98154,
    oxidationStates: [3],
    rawType: 'Metal',
  },
  {
    name: 'Americio',
    symbol: 'Am',
    atomicNumber: 95,
    atomicWeight: 243,
    oxidationStates: [6, 5, 4, 3],
    rawType: 'Actinide',
  },
  {
    name: 'Antimonio',
    symbol: 'Sb',
    atomicNumber: 51,
    atomicWeight: 121.757,
    oxidationStates: [3, -3, 5],
    rawType: 'Metalloid',
  },
  {
    name: 'Argon',
    symbol: 'Ar',
    atomicNumber: 18,
    atomicWeight: 39.948,
    oxidationStates: [],
    rawType: 'NobleGas',
  },
  {
    name: 'Arsenico',
    symbol: 'As',
    atomicNumber: 33,
    atomicWeight: 74.9216,
    oxidationStates: [3, -3, 5],
    rawType: 'Metalloid',
  },
  {
    name: 'Astato',
    symbol: 'At',
    atomicNumber: 85,
    atomicWeight: 210,
    oxidationStates: [1, -1, 3, 5, 7],
    rawType: 'Metalloid',
  },
  {
    name: 'Oro',
    symbol: 'Au',
    atomicNumber: 79,
    atomicWeight: 196.9665,
    oxidationStates: [3, 1],
    rawType: 'Metal',
  },
  {
    name: 'Boro',
    symbol: 'B',
    atomicNumber: 5,
    atomicWeight: 10.811,
    oxidationStates: [3],
    rawType: 'Metalloid',
  },
  {
    name: 'Bario',
    symbol: 'Ba',
    atomicNumber: 56,
    atomicWeight: 137.33,
    oxidationStates: [2],
    rawType: 'Metal',
  },
  {
    name: 'Berillio',
    symbol: 'Be',
    atomicNumber: 4,
    atomicWeight: 9.01218,
    oxidationStates: [2],
    rawType: 'Metal',
  },
  {
    name: 'Bohrio',
    symbol: 'Bh',
    atomicNumber: 107,
    atomicWeight: 262,
    oxidationStates: [],
    rawType: 'Metal',
  },
  {
    name: 'Bismuto',
    symbol: 'Bi',
    atomicNumber: 83,
    atomicWeight: 208.9804,
    oxidationStates: [3, 5],
    rawType: 'Metal',
  },
  {
    name: 'Berkelio',
    symbol: 'Bk',
    atomicNumber: 97,
    atomicWeight: 247,
    oxidationStates: [4, 3],
    rawType: 'Actinide',
  },
  {
    name: 'Bromo',
    symbol: 'Br',
    atomicNumber: 35,
    atomicWeight: 79.904,
    oxidationStates: [1, -1, 5],
    rawType: 'NonMetal',
  },
  {
    name: 'Carbonio',
    symbol: 'C',
    atomicNumber: 6,
    atomicWeight: 12.011,
    oxidationStates: [4, -4, 2],
    rawType: 'NonMetal',
  },
  {
    name: 'Calcio',
    symbol: 'Ca',
    atomicNumber: 20,
    atomicWeight: 40.078,
    oxidationStates: [2],
    rawType: 'Metal',
  },
  {
    name: 'Cadmio',
    symbol: 'Cd',
    atomicNumber: 48,
    atomicWeight: 112.41,
    oxidationStates: [2],
    rawType: 'Metal',
  },
  {
    name: 'Cerio',
    symbol: 'Ce',
    atomicNumber: 58,
    atomicWeight: 140.12,
    oxidationStates: [3, 4],
    rawType: 'Lanthanide',
  },
  {
    name: 'Californio',
    symbol: 'Cf',
    atomicNumber: 98,
    atomicWeight: 251,
    oxidationStates: [3],
    rawType: 'Actinide',
  },
  {
    name: 'Cloro',
    symbol: 'Cl',
    atomicNumber: 17,
    atomicWeight: 35.4527,
    oxidationStates: [1, -1, 3, 5, 7],
    rawType: 'NonMetal',
  },
  {
    name: 'Curio',
    symbol: 'Cm',
    atomicNumber: 96,
    atomicWeight: 247,
    oxidationStates: [3],
    rawType: 'Actinide',
  },
  {
    name: 'Cobalto',
    symbol: 'Co',
    atomicNumber: 27,
    atomicWeight: 58.9332,
    oxidationStates: [2, 3],
    rawType: 'Metal',
  },
  {
    name: 'Cromo',
    symbol: 'Cr',
    atomicNumber: 24,
    atomicWeight: 51.996,
    oxidationStates: [6, 3, 2],
    rawType: 'Metal',
  },
  {
    name: 'Cesio',
    symbol: 'Cs',
    atomicNumber: 55,
    atomicWeight: 132.9054,
    oxidationStates: [1],
    rawType: 'Metal',
  },
  {
    name: 'Rame',
    symbol: 'Cu',
    atomicNumber: 29,
    atomicWeight: 63.546,
    oxidationStates: [2, 1],
    rawType: 'Metal',
  },
  {
    name: 'Dubnio',
    symbol: 'Db',
    atomicNumber: 105,
    atomicWeight: 262,
    oxidationStates: [],
    rawType: 'Metal',
  },
  {
    name: 'Disprosio',
    symbol: 'Dy',
    atomicNumber: 66,
    atomicWeight: 162.5,
    oxidationStates: [3],
    rawType: 'Lanthanide',
  },
  {
    name: 'Erbio',
    symbol: 'Er',
    atomicNumber: 68,
    atomicWeight: 167.26,
    oxidationStates: [3],
    rawType: 'Lanthanide',
  },
  {
    name: 'Einsteinio',
    symbol: 'Es',
    atomicNumber: 99,
    atomicWeight: 252,
    oxidationStates: [],
    rawType: 'Actinide',
  },
  {
    name: 'Europio',
    symbol: 'Eu',
    atomicNumber: 63,
    atomicWeight: 151.965,
    oxidationStates: [3, 2],
    rawType: 'Lanthanide',
  },
  {
    name: 'Fluoro',
    symbol: 'F',
    atomicNumber: 9,
    atomicWeight: 18.9984,
    oxidationStates: [-1],
    rawType: 'NonMetal',
  },
  {
    name: 'Ferro',
    symbol: 'Fe',
    atomicNumber: 26,
    atomicWeight: 55.847,
    oxidationStates: [2, 3],
    rawType: 'Metal',
  },
  {
    name: 'Fermio',
    symbol: 'Fm',
    atomicNumber: 100,
    atomicWeight: 257,
    oxidationStates: [],
    rawType: 'Actinide',
  },
  {
    name: 'Francio',
    symbol: 'Fr',
    atomicNumber: 87,
    atomicWeight: 223,
    oxidationStates: [1],
    rawType: 'Metal',
  },
  {
    name: 'Gallio',
    symbol: 'Ga',
    atomicNumber: 31,
    atomicWeight: 69.723,
    oxidationStates: [3],
    rawType: 'Metal',
  },
  {
    name: 'Gadolinio',
    symbol: 'Gd',
    atomicNumber: 64,
    atomicWeight: 157.25,
    oxidationStates: [3],
    rawType: 'Lanthanide',
  },
  {
    name: 'Germanio',
    symbol: 'Ge',
    atomicNumber: 32,
    atomicWeight: 72.61,
    oxidationStates: [4],
    rawType: 'Metalloid',
  },
  {
    name: 'Idrogeno',
    symbol: 'H',
    atomicNumber: 1,
    atomicWeight: 1.00794,
    oxidationStates: [1],
    rawType: 'NonMetal',
  },
  {
    name: 'Elio',
    symbol: 'He',
    atomicNumber: 2,
    atomicWeight: 4.0026,
    oxidationStates: [],
    rawType: 'NobleGas',
  },
  {
    name: 'Afnio',
    symbol: 'Hf',
    atomicNumber: 72,
    atomicWeight: 178.49,
    oxidationStates: [4],
    rawType: 'Metal',
  },
  {
    name: 'Mercurio',
    symbol: 'Hg',
    atomicNumber: 80,
    atomicWeight: 200.59,
    oxidationStates: [2, 1],
    rawType: 'Metal',
  },
  {
    name: 'Olmio',
    symbol: 'Ho',
    atomicNumber: 67,
    atomicWeight: 164.9303,
    oxidationStates: [3],
    rawType: 'Lanthanide',
  },
  {
    name: 'Hassio',
    symbol: 'Hs',
    atomicNumber: 108,
    atomicWeight: 265,
    oxidationStates: [],
    rawType: 'Metal',
  },
  {
    name: 'Iodio',
    symbol: 'I',
    atomicNumber: 53,
    atomicWeight: 126.9045,
    oxidationStates: [1, -1, 3, 5, 7],
    rawType: 'NonMetal',
  },
  {
    name: 'Indio',
    symbol: 'In',
    atomicNumber: 49,
    atomicWeight: 114.82,
    oxidationStates: [3],
    rawType: 'Metal',
  },
  {
    name: 'Iridio',
    symbol: 'Ir',
    atomicNumber: 77,
    atomicWeight: 192.22,
    oxidationStates: [2, 3, 4, 6],
    rawType: 'Metal',
  },
  {
    name: 'Potassio',
    symbol: 'K',
    atomicNumber: 19,
    atomicWeight: 39.0983,
    oxidationStates: [1],
    rawType: 'Metal',
  },
  {
    name: 'Kripton',
    symbol: 'Kr',
    atomicNumber: 36,
    atomicWeight: 83.8,
    oxidationStates: [],
    rawType: 'NobleGas',
  },
  {
    name: 'Lantanio',
    symbol: 'La',
    atomicNumber: 57,
    atomicWeight: 138.9055,
    oxidationStates: [3],
    rawType: 'Lanthanide',
  },
  {
    name: 'Litio',
    symbol: 'Li',
    atomicNumber: 3,
    atomicWeight: 6.941,
    oxidationStates: [1],
    rawType: 'Metal',
  },
  {
    name: 'Laurenzio',
    symbol: 'Lr',
    atomicNumber: 103,
    atomicWeight: 262,
    oxidationStates: [],
    rawType: 'Actinide',
  },
  {
    name: 'Lutezio',
    symbol: 'Lu',
    atomicNumber: 71,
    atomicWeight: 174.967,
    oxidationStates: [3],
    rawType: 'Lanthanide',
  },
  {
    name: 'Mendelevio',
    symbol: 'Md',
    atomicNumber: 101,
    atomicWeight: 258,
    oxidationStates: [],
    rawType: 'Actinide',
  },
  {
    name: 'Magnesio',
    symbol: 'Mg',
    atomicNumber: 12,
    atomicWeight: 24.305,
    oxidationStates: [2],
    rawType: 'Metal',
  },
  {
    name: 'Manganese',
    symbol: 'Mn',
    atomicNumber: 25,
    atomicWeight: 54.938,
    oxidationStates: [7, 6, 4, 2, 3],
    rawType: 'Metal',
  },
  {
    name: 'Molibdeno',
    symbol: 'Mo',
    atomicNumber: 42,
    atomicWeight: 95.94,
    oxidationStates: [6, 5, 4, 3, 2],
    rawType: 'Metal',
  },
  {
    name: 'Meitnerio',
    symbol: 'Mt',
    atomicNumber: 109,
    atomicWeight: 266,
    oxidationStates: [],
    rawType: 'Metal',
  },
  {
    name: 'Azoto',
    symbol: 'N',
    atomicNumber: 7,
    atomicWeight: 14.0067,
    oxidationStates: [3, -3, 5, 4, 2],
    rawType: 'NonMetal',
  },
  {
    name: 'Sodio',
    symbol: 'Na',
    atomicNumber: 11,
    atomicWeight: 22.98977,
    oxidationStates: [1],
    rawType: 'Metal',
  },
  {
    name: 'Niobio',
    symbol: 'Nb',
    atomicNumber: 41,
    atomicWeight: 92.9064,
    oxidationStates: [5, 3],
    rawType: 'Metal',
  },
  {
    name: 'Neodimio',
    symbol: 'Nd',
    atomicNumber: 60,
    atomicWeight: 144.24,
    oxidationStates: [3],
    rawType: 'Lanthanide',
  },
  {
    name: 'Neon',
    symbol: 'Ne',
    atomicNumber: 10,
    atomicWeight: 20.1797,
    oxidationStates: [],
    rawType: 'NobleGas',
  },
  {
    name: 'Nichel',
    symbol: 'Ni',
    atomicNumber: 28,
    atomicWeight: 58.6934,
    oxidationStates: [2, 3],
    rawType: 'Metal',
  },
  {
    name: 'Nobelio',
    symbol: 'No',
    atomicNumber: 102,
    atomicWeight: 259,
    oxidationStates: [],
    rawType: 'Actinide',
  },
  {
    name: 'Nettunio',
    symbol: 'Np',
    atomicNumber: 93,
    atomicWeight: 237.0482,
    oxidationStates: [6, 5, 4, 3],
    rawType: 'Actinide',
  },
  {
    name: 'Ossigeno',
    symbol: 'O',
    atomicNumber: 8,
    atomicWeight: 15.9994,
    oxidationStates: [-2],
    rawType: 'NonMetal',
  },
  {
    name: 'Osmio',
    symbol: 'Os',
    atomicNumber: 76,
    atomicWeight: 190.2,
    oxidationStates: [2, 3, 4, 6, 8],
    rawType: 'Metal',
  },
  {
    name: 'Fosforo',
    symbol: 'P',
    atomicNumber: 15,
    atomicWeight: 30.97376,
    oxidationStates: [3, -3, 5, 4],
    rawType: 'NonMetal',
  },
  {
    name: 'Protoattinio',
    symbol: 'Pa',
    atomicNumber: 91,
    atomicWeight: 231.0359,
    oxidationStates: [5, 4],
    rawType: 'Actinide',
  },
  {
    name: 'Piombio',
    symbol: 'Pb',
    atomicNumber: 82,
    atomicWeight: 207.2,
    oxidationStates: [4, 2],
    rawType: 'Metal',
  },
  {
    name: 'Palladio',
    symbol: 'Pd',
    atomicNumber: 46,
    atomicWeight: 106.42,
    oxidationStates: [2, 4],
    rawType: 'Metal',
  },
  {
    name: 'Promezio',
    symbol: 'Pm',
    atomicNumber: 61,
    atomicWeight: 145,
    oxidationStates: [3],
    rawType: 'Lanthanide',
  },
  {
    name: 'Polonio',
    symbol: 'Po',
    atomicNumber: 84,
    atomicWeight: 209,
    oxidationStates: [4, 2],
    rawType: 'Metal',
  },
  {
    name: 'Praseodimio',
    symbol: 'Pr',
    atomicNumber: 59,
    atomicWeight: 140.9077,
    oxidationStates: [3, 4],
    rawType: 'Lanthanide',
  },
  {
    name: 'Platino',
    symbol: 'Pt',
    atomicNumber: 78,
    atomicWeight: 195.08,
    oxidationStates: [2, 4],
    rawType: 'Metal',
  },
  {
    name: 'Plutonio',
    symbol: 'Pu',
    atomicNumber: 94,
    atomicWeight: 244,
    oxidationStates: [6, 5, 4, 3],
    rawType: 'Actinide',
  },
  {
    name: 'Radio',
    symbol: 'Ra',
    atomicNumber: 88,
    atomicWeight: 226.0254,
    oxidationStates: [2],
    rawType: 'Metal',
  },
  {
    name: 'Rubidio',
    symbol: 'Rb',
    atomicNumber: 37,
    atomicWeight: 85.4678,
    oxidationStates: [1],
    rawType: 'Metal',
  },
  {
    name: 'Renio',
    symbol: 'Re',
    atomicNumber: 75,
    atomicWeight: 186.207,
    oxidationStates: [7, 6, 4, 2, -1],
    rawType: 'Metal',
  },
  {
    name: 'Rutherfordio',
    symbol: 'Rf',
    atomicNumber: 104,
    atomicWeight: 261,
    oxidationStates: [],
    rawType: 'Metal',
  },
  {
    name: 'Rodio',
    symbol: 'Rh',
    atomicNumber: 45,
    atomicWeight: 102.9055,
    oxidationStates: [2, 3, 4],
    rawType: 'Metal',
  },
  {
    name: 'Radon',
    symbol: 'Rn',
    atomicNumber: 86,
    atomicWeight: 222,
    oxidationStates: [],
    rawType: 'NobleGas',
  },
  {
    name: 'Rutenio',
    symbol: 'Ru',
    atomicNumber: 44,
    atomicWeight: 101.07,
    oxidationStates: [2, 3, 4, 6, 8],
    rawType: 'Metal',
  },
  {
    name: 'Zolfo',
    symbol: 'S',
    atomicNumber: 16,
    atomicWeight: 32.066,
    oxidationStates: [2, -2, 4, 6],
    rawType: 'NonMetal',
  },
  {
    name: 'Argento',
    symbol: 'Ag',
    atomicNumber: 47,
    atomicWeight: 107.868,
    oxidationStates: [1],
    rawType: 'Metal',
  },
  {
    name: 'Scandio',
    symbol: 'Sc',
    atomicNumber: 21,
    atomicWeight: 44.9559,
    oxidationStates: [3],
    rawType: 'Metal',
  },
  {
    name: 'Selenio',
    symbol: 'Se',
    atomicNumber: 34,
    atomicWeight: 78.96,
    oxidationStates: [-2, 4, 6],
    rawType: 'NonMetal',
  },
  {
    name: 'Seaborgio',
    symbol: 'Sg',
    atomicNumber: 106,
    atomicWeight: 263,
    oxidationStates: [],
    rawType: 'Metal',
  },
  {
    name: 'Silicio',
    symbol: 'Si',
    atomicNumber: 14,
    atomicWeight: 28.0855,
    oxidationStates: [4],
    rawType: 'Metalloid',
  },
  {
    name: 'Samario',
    symbol: 'Sm',
    atomicNumber: 62,
    atomicWeight: 150.36,
    oxidationStates: [3, 2],
    rawType: 'Lanthanide',
  },
  {
    name: 'Stronzio',
    symbol: 'Sr',
    atomicNumber: 38,
    atomicWeight: 87.62,
    oxidationStates: [2],
    rawType: 'Metal',
  },
  {
    name: 'Tantalio',
    symbol: 'Ta',
    atomicNumber: 73,
    atomicWeight: 180.9479,
    oxidationStates: [5],
    rawType: 'Metal',
  },
  {
    name: 'Terbio',
    symbol: 'Tb',
    atomicNumber: 65,
    atomicWeight: 158.9253,
    oxidationStates: [3, 4],
    rawType: 'Lanthanide',
  },
  {
    name: 'Tecnezio',
    symbol: 'Tc',
    atomicNumber: 43,
    atomicWeight: 98,
    oxidationStates: [7],
    rawType: 'Metal',
  },
  {
    name: 'Tellurio',
    symbol: 'Te',
    atomicNumber: 52,
    atomicWeight: 127.6,
    oxidationStates: [-2, 4, 6],
    rawType: 'Metalloid',
  },
  {
    name: 'Torio',
    symbol: 'Th',
    atomicNumber: 90,
    atomicWeight: 232.0381,
    oxidationStates: [4],
    rawType: 'Actinide',
  },
  {
    name: 'Stagno',
    symbol: 'Sn',
    atomicNumber: 50,
    atomicWeight: 118.71,
    oxidationStates: [4, 2],
    rawType: 'Metal',
  },
  {
    name: 'Titanio',
    symbol: 'Ti',
    atomicNumber: 22,
    atomicWeight: 47.88,
    oxidationStates: [4, 3],
    rawType: 'Metal',
  },
  {
    name: 'Tallio',
    symbol: 'Tl',
    atomicNumber: 81,
    atomicWeight: 204.383,
    oxidationStates: [3, 1],
    rawType: 'Metal',
  },
  {
    name: 'Tulio',
    symbol: 'Tm',
    atomicNumber: 69,
    atomicWeight: 168.9342,
    oxidationStates: [3, 2],
    rawType: 'Lanthanide',
  },
  {
    name: 'Uranio',
    symbol: 'U',
    atomicNumber: 92,
    atomicWeight: 238.029,
    oxidationStates: [6, 5, 4, 3],
    rawType: 'Actinide',
  },
  {
    name: 'Vanadio',
    symbol: 'V',
    atomicNumber: 23,
    atomicWeight: 50.9415,
    oxidationStates: [5, 4, 3, 2],
    rawType: 'Metal',
  },
  {
    name: 'Tungsteno',
    symbol: 'W',
    atomicNumber: 74,
    atomicWeight: 183.85,
    oxidationStates: [6, 5, 4, 3, 2],
    rawType: 'Metal',
  },
  {
    name: 'Xeno',
    symbol: 'Xe',
    atomicNumber: 54,
    atomicWeight: 131.29,
    oxidationStates: [],
    rawType: 'NobleGas',
  },
  {
    name: 'Ittrio',
    symbol: 'Y',
    atomicNumber: 39,
    atomicWeight: 88.9059,
    oxidationStates: [3],
    rawType: 'Metal',
  },
  {
    name: 'Itterbio',
    symbol: 'Yb',
    atomicNumber: 70,
    atomicWeight: 173.04,
    oxidationStates: [3, 2],
    rawType: 'Lanthanide',
  },
  {
    name: 'Zinco',
    symbol: 'Zn',
    atomicNumber: 30,
    atomicWeight: 65.39,
    oxidationStates: [2],
    rawType: 'Metal',
  },
  {
    name: 'Zirconio',
    symbol: 'Zr',
    atomicNumber: 40,
    atomicWeight: 91.224,
    oxidationStates: [4],
    rawType: 'Metal',
  },
];
